#!/bin/sh

. /etc/formfactor/config

if [ "$HAVE_TOUCHSCREEN" = "1" ]; then
    SHOWCURSOR="no"
else
    SHOWCURSOR="yes"
fi

if [ "$HAVE_KEYBOARD" = "1" ]; then
    KEYBOARD_APPLET=""
else
    KEYBOARD_APPLET="keyboard"
fi

SHOWTITLEBAR="no"

# Tell GTK+3 we really want server side decorations, even with
# GtkHeaderBar using applications: Without that mb-panel will render
# on top of the client side decorations.
export GTK_CSD=0

#matchbox-desktop &

# Lines containing feature-[foo] are removed at build time if the machine
# doesn't have the feature "foo".

#START_APPLETS=showdesktop,windowselector
#END_APPLETS=clock,battery,$KEYBOARD_APPLET,systray,startup-notify,notify

#matchbox-panel --titlebar --start-applets $START_APPLETS --end-applets $END_APPLETS &

#exec matchbox-window-manager -theme Sato -use_desktop_mode decorated -use_cursor $SHOWCURSOR $@
exec matchbox-window-manager -theme Sato -use_desktop_mode plain -use_cursor $SHOWCURSOR -use_titlebar $SHOWTITLEBAR $@

